#server:
#  port: 13000
#spring:
#  application:
#    name: service-record-api
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#    sentinel:
#      transport:
#        port: 23000
#        dashboard: 30000
#  datasource:
#    username: root
#    password: ACDCacdc120
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://127.0.0.1:3306/leafbook?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
#    driver-class-name: com.mysql.cj.jdbc.Driver
#swagger:
#  title: service-record-api
#  version: 1.0.0
#  base-package: org.leafbook.serviceTopicApi
#  description: "service record api"
#  group-name: service-record-api
#snowflake:
#  datacenterId: 1
#  workId: 3
#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**