server:
  port: 13000
spring:
  application:
    name: servie-record-api
  cloud:
    nacos:
      discovery:
        server-addr: ${HOSTS:localhost:8848}
    sentinel:
      transport:
        port: 23000
        dashboard: 30000
swagger:
  base-package: org.leafbook.serviceRecordApi
  description: "serviceRecordApi"
  group-name: "serviceRecordApi"