server:
  port: 10000
spring:
  application:
    name: service-common-api
  cloud:
    nacos:
      discovery:
        server-addr: ${HOSTS:localhost:8848}
    sentinel:
      transport:
        port: 20000
        dashboard: HOSTS:localhost:30000
rocketmq:
  namesrvAddr: 192.168.50.245:9876
  producer:
    group: demo
