#server:
#  port: 10001
#spring:
#  application:
#    name: service-common-api
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#    sentinel:
#      transport:
#        port: 20000
#        dashboard: HOSTS:localhost:30000
#  datasource:
#    username: root
#    password: ACDCacdc120
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://127.0.0.1:3306/leafbook?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
#    driver-class-name: com.mysql.cj.jdbc.Driver
#rocketmq:
#  namesrvAddr: 192.168.50.245:9876
#  producer:
#    group: email
#swagger:
#  title: service-common-api
#  version: 1.0.0
#  base-package: org.leafbook.serviceCommonApi
#  description: "service common api"
#  group-name: service-common-api
#snowflake:
#  datacenterId: 1
#  workId: 7
#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**
