server:
  port: 11001
spring:
  application:
    name: service-user-api
  cloud:
    nacos:
      discovery:
        server-addr: ${HOSTS:localhost:8848}
    sentinel:
      transport:
        port: 21000
        dashboard: localhost:30000
