server:
  port: 16000
spring:
  application:
    name: service-comment-api
  cloud:
    nacos:
      discovery:
        server-addr: ${HOSTS:localhost:8848}
    sentinel:
      transport:
        port: 26000
        dashboard: HOSTS:localhost:30000
