server:
  port: 17000
spring:
  application:
    name: service-gateway-api
  cloud:
    nacos:
      discovery:
        server-addr: ${HOSTS:localhost:8848}
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: serviceUserApi
          uri: lb://service-api
          predicates:
            - Path=/api/**

